spring.application.name=ecommerce

# ===============================
# MYSQL CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=ecommerce_user
spring.datasource.password=ecommerce_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# configure mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hachmail88@gmail.com
spring.mail.password=sdsezvujgpiqtopc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
